[[entity]]

    [entity.components.Text]
    id = "title"
    text = "Arkanoid"
    font_face = { font = "joystix", options = { size = 80.0, hinting = "Full" } }
    color = [255, 255, 255, 255]

    [entity.components.UITransform]
    translation = { x = 360, y = 500 }

[[entity]]

    [entity.components.Text]
    id = "courtesy"
    text = "2020 Arkanoid and its authors."
    font_face = { font = "joystix", options = { size = 25.0, hinting = "Full" } }
    color = [255, 255, 255, 255]

    [entity.components.UITransform]
    translation = { x = 360, y = 300 }

[[entity]]

    [entity.components.Text]
    id = "cursor_main_menu"
    text = "\u25ba"
    font_face = { font = "hack", options = { size = 40.0, hinting = "Full" } }
    color = [255, 255, 255, 0]

    [entity.components.UITransform]
    translation = { x = 165, y = 200 }
    
[[entity]]

    [entity.components.Text]
    id = "main_menu"
    text = "MAIN MENU"
    font_face = { font = "joystix", options = { size = 40.0, hinting = "Full" } }
    color = [255, 255, 255, 255]

    [entity.components.UITransform]
    translation = { x = 360, y = 200 }


[[entity]]

    [entity.components.SpriteRender]
    fill = { width = 310, height = 40 }

    [entity.components.Transform]
    translation = { x = 360.0, y = 200.0 }

    [entity.components.MouseReactive]
    id = "main_menu"

